onlyBuiltDependencies:
  - '@parcel/watcher'
  - core-js
  - es5-ext
  - fsevents
  - pre-commit
  - spawn-sync

overrides:
  braces@<3.0.3: '>=3.0.3'
  cross-spawn@<6.0.6: '>=6.0.6'
  ejs@<2.5.3: '>=2.5.5'
  ejs@<2.5.5: '>=2.5.5'
  ejs@<3.1.10: '>=3.1.10'
  ejs@<3.1.7: '>=3.1.7'
  micromatch@<4.0.8: '>=4.0.8'
  serialize-javascript@<=7.0.2: '>=7.0.3'
  serialize-javascript@>=5.0.0 <7.0.5: '>=7.0.5'
  uuid@<11.1.1: '>=11.1.1'
